import React, { useState, useEffect } from 'react';
import { Icon } from '../components/Icons';
import { DataService } from '../lib/api';
import { CaseEditorModal } from './CaseEditorModal';
import { CaseSimulationModal } from '../components/CaseSimulationModal';
import { Modal } from '../components/Modal';

export const CasesView = ({ onShowToast, lang = 'uz' }) => {
  const [cases, setCases] = useState([]);
  const [categories, setCategories] = useState([]);
  const [topics, setTopics] = useState([]);

  // Filters
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('');
  const [selectedTopic, setSelectedTopic] = useState('');
  const [selectedDifficulty, setSelectedDifficulty] = useState('');
  const [selectedStatus, setSelectedStatus] = useState('');

  // Modals state
  const [isEditorOpen, setIsEditorOpen] = useState(false);
  const [editingCase, setEditingCase] = useState(null);

  const [isSimModalOpen, setIsSimModalOpen] = useState(false);
  const [simCase, setSimCase] = useState(null);

  const [isAiGenModalOpen, setIsAiGenModalOpen] = useState(false);
  const [aiGenPrompt, setAiGenPrompt] = useState({
    topic: 'O\'tkir Appenditsit',
    difficulty: 'medium',
    chief_complaint: 'O\'ng yonbosh sohasidagi o\'tkir og\'riq, ko\'ngil aynishi, 37.8 harorat'
  });
  const [isAiGenerating, setIsAiGenerating] = useState(false);

  // Load data
  const loadAll = () => {
    setCases(DataService.getCases());
    setCategories(DataService.getCategories());
    setTopics(DataService.getTopics());
  };

  useEffect(() => {
    loadAll();
  }, []);

  // Filter cases
  const filteredCases = cases.filter(c => {
    const titleMatch = (c.title?.[lang] || c.title?.uz || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
                       (c.subtitle?.[lang] || c.subtitle?.uz || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
                       (c.chief_complaint?.[lang] || c.chief_complaint?.uz || '').toLowerCase().includes(searchTerm.toLowerCase());

    const catMatch = !selectedCategory || c.category_id === selectedCategory;
    const topMatch = !selectedTopic || c.topic_id === selectedTopic;
    const diffMatch = !selectedDifficulty || c.difficulty === selectedDifficulty;
    const statusMatch = !selectedStatus || c.status === selectedStatus;

    return titleMatch && catMatch && topMatch && diffMatch && statusMatch;
  });

  const handleSaveCase = (casePayload) => {
    DataService.saveCase(casePayload);
    setIsEditorOpen(false);
    setEditingCase(null);
    loadAll();
    onShowToast("Klinik keys muvaffaqiyatli saqlandi!", "success");
  };

  const handleDeleteCase = (id) => {
    if (window.confirm("Haqiqatan ham bu klinik keysni o'chirmoqchimisiz?")) {
      DataService.deleteCase(id);
      loadAll();
      onShowToast("Keys o'chirildi.", "warning");
    }
  };

  const handleTogglePublish = (id) => {
    DataService.togglePublishCase(id);
    loadAll();
    onShowToast("Keys nashr holati yangilandi!", "info");
  };

  const handleRunAiGenerate = () => {
    setIsAiGenerating(true);
    setTimeout(() => {
      setIsAiGenerating(false);
      const generatedCase = {
        title: {
          uz: `${aiGenPrompt.topic} — AI Klinik Stsenariysi`,
          ru: `${aiGenPrompt.topic} — Клинический сценарий`,
          en: `${aiGenPrompt.topic} — AI Clinical Case`
        },
        subtitle: {
          uz: "AI tomonidan avtomatik generatsiya qilingan tibbiy simulyatsiya keysi",
          ru: "Клинический кейс, сгенерированный ИИ",
          en: "Clinical case generated by TibSphere AI"
        },
        chief_complaint: {
          uz: aiGenPrompt.chief_complaint,
          ru: aiGenPrompt.chief_complaint,
          en: aiGenPrompt.chief_complaint
        },
        difficulty: aiGenPrompt.difficulty,
        status: "draft",
        patient_age: 26,
        patient_gender: "male",
        visual_state: "sweating_pale",
        expected_duration_minutes: 15,
        is_ai_generated: true,
        order_num: cases.length + 1,
        category_id: categories[0]?.id || "cat-1",
        topic_id: topics[0]?.id || "top-1",
        initial_vitals: {
          blood_pressure: "125/80 mmHg",
          heart_rate: 92,
          temperature: 37.8,
          spo2: 98,
          respiratory_rate: 18
        },
        scenario: {
          patient_history: "Bemor 8 soat oldin epigastral sohada og'riq sezgan, keyinchalik og'riq o'ng yonbosh sohasiga ko'chgan (Kocher-Volkovich simptomi).",
          physical_exam: "O'ng yonbosh sohasida qorin devorining tarangligi, Shchetkin-Blumberg va Voskresenskiy simptomlari musbat.",
          ecg_findings: "Sinus ritmi, 92 bpm.",
          lab_tests: {
            leukocytes: "13.4 x 10^9/l",
            neutrophils_shift: "Tayoqchasimonlar 12%"
          },
          differential_diagnoses: ["O'tkir appenditsit", "O'tkir mezadenit", "Buyrak sanchig'i"],
          treatment_steps: ["Shoshilinch xirurgik ko'rik", "Appendektomiya (laparoskopik)", "Antibiotikoprofilaktika"]
        },
        expected_answer: "O'tkir flegmonoz appenditsit. Shoshilinch xirurgik operatsiya — laparoskopik appendektomiya ko'rsatilgan."
      };

      DataService.saveCase(generatedCase);
      setIsAiGenModalOpen(false);
      loadAll();
      onShowToast("✨ Yangi keys AI yordamida muvaffaqiyatli generatsiya qilindi!", "success");
    }, 1200);
  };

  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Top Action Bar */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '14px' }}>
        <div>
          <h2 style={{ fontSize: '1.35rem', color: '#fff', fontWeight: '800' }}>Klinik Case'lar Boshqaruvi</h2>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            Jami: <strong>{filteredCases.length}</strong> ta keys topildi
          </div>
        </div>

        <div style={{ display: 'flex', gap: '10px' }}>
          <button
            onClick={() => setIsAiGenModalOpen(true)}
            className="btn-secondary"
            style={{ borderColor: 'rgba(139, 92, 246, 0.4)', color: 'var(--accent-purple)' }}
          >
            <Icon name="sparkles" size={16} color="var(--accent-purple)" />
            <span>AI Bilan Generatsiya</span>
          </button>

          <button
            onClick={() => {
              setEditingCase(null);
              setIsEditorOpen(true);
            }}
            className="btn-primary"
          >
            <Icon name="plus" size={16} />
            <span>Yangi Keys Yaratish</span>
          </button>
        </div>
      </div>

      {/* Filters & Search Card */}
      <div className="glass-panel" style={{ padding: '16px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '12px' }}>
          {/* Search */}
          <div style={{ position: 'relative', gridColumn: 'span 2' }}>
            <input
              type="text"
              className="form-input"
              style={{ paddingLeft: '36px' }}
              placeholder="Keys nomi, shikoyat yoki kalit so'z bo'yicha qidiruv..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            <div style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }}>
              <Icon name="search" size={16} />
            </div>
          </div>

          {/* Category Filter */}
          <select
            className="form-select"
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
          >
            <option value="">Barcha Bo'limlar</option>
            {categories.map(c => (
              <option key={c.id} value={c.id}>{c.name?.[lang] || c.name?.uz}</option>
            ))}
          </select>

          {/* Difficulty Filter */}
          <select
            className="form-select"
            value={selectedDifficulty}
            onChange={(e) => setSelectedDifficulty(e.target.value)}
          >
            <option value="">Barcha Qiyinlik</option>
            <option value="easy">Oson (Easy)</option>
            <option value="medium">O'rta (Medium)</option>
            <option value="hard">Qiyin (Hard)</option>
          </select>

          {/* Status Filter */}
          <select
            className="form-select"
            value={selectedStatus}
            onChange={(e) => setSelectedStatus(e.target.value)}
          >
            <option value="">Barcha Holat</option>
            <option value="published">Nashr qilingan</option>
            <option value="draft">Qoralama</option>
          </select>
        </div>
      </div>

      {/* Cases Table */}
      <div className="data-table-container">
        <table className="data-table">
          <thead>
            <tr>
              <th>Keys Ma'lumoti</th>
              <th>Yo'nalish / Mavzu</th>
              <th>Bemor Profili</th>
              <th>Qiyinlik</th>
              <th>Holat</th>
              <th>Turi</th>
              <th style={{ textAlign: 'right' }}>Amallar</th>
            </tr>
          </thead>
          <tbody>
            {filteredCases.length === 0 ? (
              <tr>
                <td colSpan={7} style={{ textAlign: 'center', padding: '36px', color: 'var(--text-muted)' }}>
                  Hech qanday klinik keys topilmadi.
                </td>
              </tr>
            ) : (
              filteredCases.map(c => (
                <tr key={c.id}>
                  <td style={{ maxWidth: '300px' }}>
                    <div style={{ fontWeight: '600', color: '#fff', fontSize: '0.9rem' }}>
                      {c.title?.[lang] || c.title?.uz}
                    </div>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {c.chief_complaint?.[lang] || c.chief_complaint?.uz}
                    </div>
                  </td>
                  <td>
                    <div className="badge badge-slate" style={{ marginBottom: '4px' }}>
                      {c.category_name?.[lang] || c.category_name?.uz || 'Kardiologiya'}
                    </div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                      {c.topic_name?.[lang] || c.topic_name?.uz || 'OKS'}
                    </div>
                  </td>
                  <td>
                    <div style={{ fontSize: '0.82rem', fontWeight: '500' }}>
                      {c.patient_age} yosh, {c.patient_gender === 'male' ? 'Erkak' : 'Ayol'}
                    </div>
                    <div style={{ fontSize: '0.72rem', color: 'var(--accent-cyan)', fontFamily: 'var(--font-mono)' }}>
                      BP: {c.initial_vitals?.blood_pressure}
                    </div>
                  </td>
                  <td>
                    <span className={`badge ${c.difficulty === 'easy' ? 'badge-emerald' : c.difficulty === 'medium' ? 'badge-cyan' : 'badge-rose'}`}>
                      {c.difficulty.toUpperCase()}
                    </span>
                  </td>
                  <td>
                    <button
                      onClick={() => handleTogglePublish(c.id)}
                      className={`badge ${c.status === 'published' ? 'badge-emerald' : 'badge-amber'}`}
                      style={{ cursor: 'pointer', border: 'none' }}
                      title="Holatni o'zgartirish uchun bosing"
                    >
                      {c.status === 'published' ? '● Faol (Published)' : '○ Qoralama'}
                    </button>
                  </td>
                  <td>
                    {c.is_ai_generated ? (
                      <span className="badge badge-purple">
                        <Icon name="sparkles" size={11} color="var(--accent-purple)" />
                        AI Gen
                      </span>
                    ) : (
                      <span className="badge badge-slate">Shifokor</span>
                    )}
                  </td>
                  <td style={{ textAlign: 'right' }}>
                    <div style={{ display: 'inline-flex', gap: '6px' }}>
                      {/* Simulation Test */}
                      <button
                        onClick={() => {
                          setSimCase(c);
                          setIsSimModalOpen(true);
                        }}
                        className="btn-icon"
                        title="Simulyatsiya Sinovi"
                        style={{ color: 'var(--accent-cyan)' }}
                      >
                        <Icon name="play" size={16} />
                      </button>

                      {/* Edit */}
                      <button
                        onClick={() => {
                          setEditingCase(c);
                          setIsEditorOpen(true);
                        }}
                        className="btn-icon"
                        title="Tahrirlash"
                      >
                        <Icon name="edit" size={16} />
                      </button>

                      {/* Delete */}
                      <button
                        onClick={() => handleDeleteCase(c.id)}
                        className="btn-icon"
                        title="O'chirish"
                        style={{ color: 'var(--accent-rose)' }}
                      >
                        <Icon name="trash" size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Editor Modal */}
      <CaseEditorModal
        isOpen={isEditorOpen}
        onClose={() => {
          setIsEditorOpen(false);
          setEditingCase(null);
        }}
        caseItem={editingCase}
        categories={categories}
        topics={topics}
        onSave={handleSaveCase}
        lang={lang}
      />

      {/* Simulation Modal */}
      <CaseSimulationModal
        isOpen={isSimModalOpen}
        onClose={() => {
          setIsSimModalOpen(false);
          setSimCase(null);
        }}
        caseData={simCase}
        lang={lang}
      />

      {/* AI Generator Modal */}
      <Modal
        isOpen={isAiGenModalOpen}
        onClose={() => setIsAiGenModalOpen(false)}
        title="✨ TibSphere AI Bilan Klinik Keys Generatsiya Qilish"
        maxWidth="600px"
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
            Mavzu va shikoyatni kiritsangiz, sun'iy intellekt xalqaro tibbiy protokollar asosida to'liq laboratoriya, EKG, differentsial tashxis va standart davo bosqichlarini tuzib beradi.
          </p>

          <div className="form-group">
            <label className="form-label">Tibbiy Mavzu / Kasallik:</label>
            <input
              className="form-input"
              value={aiGenPrompt.topic}
              onChange={(e) => setAiGenPrompt({ ...aiGenPrompt, topic: e.target.value })}
              placeholder="Masalan: O'tkir pankreatit, Pnevmoniya..."
            />
          </div>

          <div className="form-group">
            <label className="form-label">Qiyinlik Darajasi:</label>
            <select
              className="form-select"
              value={aiGenPrompt.difficulty}
              onChange={(e) => setAiGenPrompt({ ...aiGenPrompt, difficulty: e.target.value })}
            >
              <option value="easy">Oson (Easy)</option>
              <option value="medium">O'rta (Medium)</option>
              <option value="hard">Qiyin (Hard)</option>
            </select>
          </div>

          <div className="form-group">
            <label className="form-label">Bemor Shikoyati (Asosiy Simptomlar):</label>
            <textarea
              className="form-textarea"
              rows={3}
              value={aiGenPrompt.chief_complaint}
              onChange={(e) => setAiGenPrompt({ ...aiGenPrompt, chief_complaint: e.target.value })}
            />
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '10px' }}>
            <button onClick={() => setIsAiGenModalOpen(false)} className="btn-secondary">
              Bekor qilish
            </button>
            <button
              onClick={handleRunAiGenerate}
              disabled={isAiGenerating}
              className="btn-primary"
              style={{ background: 'linear-gradient(135deg, #8b5cf6 0%, #3b82f6 100%)' }}
            >
              <Icon name="sparkles" size={16} />
              <span>{isAiGenerating ? "AI Generatsiya Qilmoqda..." : "Keysni Generatsiya Qilish"}</span>
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
};
